### ISSUE TITLE
[Feature Request] Use of multiple currencies

### ISSUE THREAD

**Issue by Hanxyz13** [h4h13/Paisa#457]
Supports selection of multiple currencies，rather than only one currency.

**Comment by tahayparker** [comment]
alternatively, multiple accounts for different currencies

**Comment by Hanxyz13** [comment]
> alternatively, multiple accounts for different currencies

Ooh, this might be better.

**Comment by jaredkz** [comment]
I've been working on implementing this as I go along, however there are some challenges to this that make this task a little more complicated. 

Mixed currency is difficult because the display of the totals are designed for one currency, so without major changes and workarounds, this isn't the top strategy. 

- add currency as a value to account, because mixed currencies would be difficult to manage. 
- Will have to modify create account for multiple currencies, defaulting to the user-set currency/language.
- Balances throughout the app will have to be updated to fetch the correct symbol for the currency.
- Make sure this all gets backed up and stored, as well as managing for older backups that don't have these fields by default, without breaking changes.

It's doable, just a bit of work to go into it.

**Comment by h4h13** [comment]
Hey since we're not doing this hence closing it
